#!/bin/bash
#
# Sets biases on all TESs, either individually with a list of values, or
# globally with a single argument.
#
# Usage: smurf_bias_tess <bias-values>
#
# Arguments:
#  $1 -- A list of values (for each bias line), or else a single value
#        for all lines (DAC counts).
#
# Author: Attila Kovacs
# Version: 21 November 2018

SCRIPTS="$HOME/smurf/scripts"
BIAS_CONVERT="$SCRIPTS/smurf_bias_convert"


if [ $# -eq 1 ] ; then
  echo "Set SMURF TES bias on group for all to $1..."
  CURRENT=`$BIAS_CONVERT $1`
  $SCRIPTS/smurf_cmd --tes-bias --bias-group -1 --bias-current $CURRENT
else
  CURRENT=""
  GROUP=1
  for value in $* ; do
    echo "Set SMURF TES bias on group $GROUP to $value..."
    CURRENT=`$BIAS_CONVERT $value`
    $SCRIPTS/smurf_cmd --tes-bias --bias-group $GROUP --bias-current $CURRENT
    GROUP=$((GROUP++))
  done
fi


