#!/bin/bash
#
# Convert MCE DAC counts to SMuRF DAC biases in V
# SMuRF commands in volts, not current, so this is slightly cleaner
#
# For reference, SMuRF bias line resistances are about 2kOhms in high current mode, 
# 20kOhms in low current mode. 
#
# MCE DAC units are 16-bit, but the full dynamic range doesn't look like it is used. 
# Therefore MCE units 65000 (in trans_TES) will bypass this conversion and just 
# command a SMuRF delatch.
#
# Conversions are based on:
# mce_full_loadcurve = bias high 12000 DAC units = 1.5V high current mode
#
# CY 20181223

HIGH_CURRENT_MODE=true # which bias line resistors are being used in SMuRF cryocard
high_low_ratio=10.15 # measured by Dan and Cyndia 20181217 on cryocard C01-01

if $HIGH_CURRENT_MODE; then
    echo "scale=6; $1 / 8000." | bc
else
    echo "scale=6; $1 * high_low_ratio / 8000." | bc
fi
