#!/bin/bash
#
# Tunes SMURF resonators to with last search values.
#
# Author: Attila Kovacs
# Version: 23 October 2018

SCRIPTS="$HOME/smurf/scripts"

echo "Use last SMURF tuning..."
$HOME/smurf_cmd --last-tune

# Send completion signal to GCP (exits on error)...
source $SCRIPTS/gcp_signal $?
