#!/bin/bash
#
# Sets the SMURF TES bias on the specified group to the specified voltage 
# value (uV)
#
# Usage: smurf_tes_bias <group-number> <bias-counts>
#
# Arguments:
#  $1 -- readout/bias group (card) number
#  $2 -- bias value (DAC counts)
#
# Author: Attila Kovacs
# Version: 23 October 2018

BIAS_CONVERT="$HOME/smurf/scripts/smurf_bias_convert"

CURRENT=`$BIAS_CONVERT $2`

echo "Set SMURF TES bias on group $1 to $2..."
$HOME/smurf_cmd --tes-bias --bias-group $1 --bias-current $CURRENT

