#!/bin/bash
#
# Tunes SMURF resonators to with last search values.
#
# Author: Attila Kovacs
# Version: 23 October 2018


echo "Use last SMURF tuning..."
$HOME/smurf_cmd --last-tune

# send signal that we're done?
$GCP_DIR/../scripts/keck/controlSystem command 'signal/send done'
