#!/bin/bash
#
# Creates a SMURF runfile.
#
# Author: Attila Kovacs
# Version: 15 November 2018

# Get num_rows / row_len / data rate from the syncbox...
ssh -t bicep51 bin/syncbox-extract.py > $HOME/smurf/scripts/state/syncbox

# Load the syncbox parameters (shell vars) from the file just created...
source $HOME/smurf/scripts/state/syncbox

echo "Create SMURF runfile for GCP..."
$HOME/smurf_cmd --make-runfile --row-len $ROW_LEN --num-rows $NUM_ROWS --data-rate $DATA_RATE > /data/cryo/mas_data_pipe.run

echo $?
