#!/bin/bash
#
# Soft resets the SMURF hardware
#
# Author: Attila Kovacs
# Version: 23 October 2018

SCRIPTS="$HOME/smurf/scripts"

echo "Soft reset SMURF..."
result=$HOME/smurf_cmd --soft-reset 
$HOME/smurf_cmd --check-lock # currently this is empty

result=$?

# send both host specific and generic done signals

$GCP_DIR/../scripts/keck/controlSystem command "log \"check_disable_reset completed on host $(hostname)\""

# Send completion signal to GCP (both specific and generic)...
$SCRIPTS/gcp_signal $result 1		# e.g. "done34"/"quit34", no exit
source $SCRIPTS/gcp_signal $result	# "done"/"quit", exit on error

