#!/bin/bash
#
# Forwards a command to execute on the SMURF server
#
# Author: Attila Kovacs <attila.kovacs@cfa.harvard.edu>
# Version: 17 October 2018
#

# Remore call via SSH tunnel to the SMuRF computer
#ssh -t cryo@smurf-srv03-gcp ${1+"$@"}
ssh -t cryo@192.168.3.4 ${1+"$@"}
