#!/bin/bash
#
# Use the tuning stored in the specified path argument
#
# Author: Attila Kovacs
# Version: 23 October 2018

SCRIPTS="$HOME/smurf/scripts"

# CY: do we need to stop acq to be safe?
# AK: No, GCP and schedules are supposed to make sure of that before calling...

echo "Use SMURF tuning at $1..."
$HOME/smurf_cmd --use-tune $1

# Send completion signal to GCP (exits on error)...
source $SCRIPTS/gcp_signal $?
