#!/bin/bash
#
# Generate partial IV curve data using the terporary saved parameters...
#
# Author: Attila Kovacs
# Version: 23 October 2018

SCRIPTS="$HOME/smurf/scripts"
PLC_FILE=$SCRIPTS/state/plc.parms

source $PLC_FILE

if [ "$STREAM_ON" -gt "0" ] ; then
 $SCRIPTS/smurf_make_runfile
 $SCRIPTS/smurf_frameacq_stamp >> /data/cryo/mas_data_pipe.run
fi

echo "Generate a partial IV curve SMURF..."
$HOME/smurf_cmd --plc --iv-bias-high $BIAS_START --iv-bias-step $BIAS_STEP --iv-wait-time $BIAS_DWELL

# Send completion signal to GCP (exits on error)...
source $SCRIPTS/gcp_signal $?
