#!/bin/bash
#
# Forwards a command to execute on the SMURF server
#
# Author: Attila Kovacs <attila.kovacs@cfa.harvard.edu>
# Version: 17 October 2018
#

# Remore call via SSH tunnel to the SMuRF computer
ssh -t cryo@131.142.156.47 ${1+"$@"}

# Return with the result of the remote call.
return $?
