#!/bin/bash
#
# Switch to using the native MCE-version of common commands, such as mce_cmd or
# mce_tes_bias...
#
# Author: Attila Kovacs <attila.kovacs@cfa.harvard.edu>
# Version: 15 November 2018
#

SCRIPTS="$HOME/smurf/scripts"
MCESCRIPTS="$HOME/gcp/masd/keck/scripts"

CURRENT_DIR=`pwd`

cd /usr/mce/bin

# Link mce_cmd to the original MCE version...
if [ -f mce_cmd.mce ] ; then
  rm -f mce_cmd
  ln -s mce_cmd.mce mce_cmd
fi

# Link mce_status to the original MCE version...
if [ -f mce_status.mce ] ; then
  rm -f mce_status
  ln -s mce_status.mce mce_status
fi

# Indetify the correct MCE script directory under /usr/mce
if [ -d /usr/mce/script ] ; then
  cd /usr/mce/script
elif [ -d /usr/mce/mce_script/script ] ; then
  cd /usr/mce/mce_script/script
else
  echo "WARNING! script directory in /usr/mce not found."
  if [ -L mce_zero_bias ] ; then
    echo "         Removing SMuRF version of mce_zero_bias from /usr/mce/bin"
    rm -f mce_zero_bias
  fi
fi


# Link mce_zero_bias to the original MCE version...
if [ -f mce_zero_bias.mce ] ; then
  rm -f mce_zero_bias
  ln -s mce_zero_bias.mce mce_zero_bias
fi



cd $CURRENT_DIR


if [ ! -d $MCESCRIPTS/mce ] ; then
  echo "Original MCE scripts are still in place in $MCESCRIPTS"
  exit 0
fi


# Remove all existing symlinks from the MASD scripts folder
source $SCRIPTS/remove_command_links.sh

CURRENT_DIR=`pwd`
cd $MCESCRIPTS

# Create symlinks for all the MCE bash scripts in the MASD scripts folder
for command in mce/* ; do
  ln -s $command .
done

cd $CURRENT_DIR

echo "Using MCE-version of common commands..."

